ALTER TABLE assignments
    ADD COLUMN IF NOT EXISTS basis_type VARCHAR(20) NOT NULL DEFAULT 'MERCHANT_NET';

ALTER TABLE assignments
    ADD COLUMN IF NOT EXISTS source_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;
